// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    Dropdown: typeof import('./components/Navbar/Dropdown.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NavbarToggleButton: typeof import('./components/Navbar/NavbarToggleButton.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    NavLink: typeof import('./components/Navbar/NavLink.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./components/Navbar/test.vue')['default']
  }
}
